server:
  port: 8083
spring:
  sleuth:
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: jorgebo10
    password: ryfypfjsgxxgojcu
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: NotificationGatewayServices
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /api/notifications/gateway/healthcheck
        healthCheckInterval: 20s
  zipkin:
    baseUrl: http://localhost:9411
twilio:
  username: AC43016ecf7ce9e3e7c1fb5712f5c2b487
  password: 892ba9f62c225b2c8685552dbb92c148
  fromPhoneNumber: +1520866013
emil:
  from: jorgebo10@gmail.com
management:
  endpoints:
    web:
      exposure:
        include: prometheus
    enabled-by-default: true
